// Auto-generated by scripts/sync-navigation.mjs
// Do not edit manually.
export const generatedNav = [
  {
    text: 'Navigate',
    link: '/start-here/'
  },
  {
    text: 'Support',
    link: '/fix/'
  },
  {
    text: 'Operate',
    link: '/playbook/'
  }
] as const
export const generatedSidebar = [
  {
    text: 'Navigate',
    collapsed: false,
    items: [
      {
        text: 'Overview',
        link: '/start-here/'
      },
      {
        text: 'Wayfinding shortcuts',
        link: '/start-here/find'
      },
      {
        text: 'State',
        link: '/state/'
      },
      {
        text: 'New joiner FAQ',
        link: '/faq-new-joiners'
      },
      {
        text: 'Monthly cadence',
        link: '/monthly-release'
      },
      {
        text: 'SLI states map',
        link: '/start-here/sli-states'
      },
      {
        text: 'Band A guardrails',
        link: '/band-a'
      }
    ]
  },
  {
    text: 'Operate',
    collapsed: false,
    items: [
      {
        text: '20-minute handover',
        link: '/runbooks/handover-20-min'
      },
      {
        text: 'All runbooks',
        link: '/runbooks/'
      },
      {
        text: 'Decision spine',
        link: '/decision-spine'
      },
      {
        text: 'Sanitization checklist',
        link: '/sanitization'
      },
      {
        text: 'Playbook canon',
        link: '/playbook/'
      },
      {
        text: 'Answer ledger pattern',
        link: '/answer-ledger'
      },
      {
        text: 'Facilitation patterns',
        link: '/facilitation'
      },
      {
        text: 'Handover RACI template',
        link: '/runbooks/handover-raci-template'
      },
      {
        text: 'Link Integrity',
        link: '/runbooks/link-integrity'
      },
      {
        text: 'North Star & Guardrails',
        link: '/playbook/north-star-guardrails'
      },
      {
        text: 'Accessibility audit',
        link: '/runbooks/accessibility-audit'
      },
      {
        text: 'Accessibility quick wins',
        link: '/accessibility-quick-wins'
      },
      {
        text: 'Anti-drift governance',
        link: '/governance'
      },
      {
        text: 'Verify-in-10 guide',
        link: '/playbook/verify-in-10'
      },
      {
        text: 'Community meeting pack',
        link: '/runbooks/community-pack'
      },
      {
        text: 'Policy-to-action example',
        link: '/pattern-expense-sla'
      },
      {
        text: 'Transition promises',
        link: '/runbooks/transition-operating-promises'
      },
      {
        text: 'Shared metric visibility',
        link: '/runbooks/shared-metric-visibility'
      },
      {
        text: 'State visibility map',
        link: '/runbooks/state-visibility'
      },
      {
        text: 'Cloudflare analytics',
        link: '/runbooks/cloudflare-analytics'
      },
      {
        text: 'Signal Registry',
        link: '/runbooks/signal-registry'
      }
    ]
  },
  {
    text: 'Support',
    collapsed: false,
    items: [
      {
        text: 'Fix: Interrupt flows',
        link: '/fix/'
      },
      {
        text: 'Fix: Teams notifications',
        link: '/fix/teams-notifications'
      },
      {
        text: 'Fix: Repo & pipeline access',
        link: '/fix/access-repo-pipeline'
      }
    ]
  }
] as const
